apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: db
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mysql
      app: db
      project: expense
  template:
    metadata:
      labels:
        name: mysql
        app: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: promptforai/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    name: mysql
    app: db
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: {{ .Values.ports.serviceport }}  # service port
    targetPort: {{ .Values.ports.containerport }} # containerport

